/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as ProjectsRouteRouteImport } from './routes/projects/route'
import { Route as ArticlesRouteRouteImport } from './routes/articles/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AccountRouteRouteImport } from './routes/account/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ArticlesIndexRouteImport } from './routes/articles/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as ProjectsIdRouteImport } from './routes/projects/$id'
import { Route as ArticlesCreateRouteImport } from './routes/articles/create'
import { Route as ArticlesUserIdRouteImport } from './routes/articles/$userId'
import { Route as ArticlesSlugRouteImport } from './routes/articles/$slug'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AccountVerifyRouteImport } from './routes/account/verify'
import { Route as AccountSettingsRouteImport } from './routes/account/settings'
import { Route as AccountResetPasswordRouteImport } from './routes/account/reset-password'
import { Route as AccountRegisterRouteImport } from './routes/account/register'
import { Route as AccountForgotPasswordRouteImport } from './routes/account/forgot-password'
import { Route as AdminUsersRouteRouteImport } from './routes/admin/users/route'
import { Route as AdminProjectsRouteRouteImport } from './routes/admin/projects/route'
import { Route as AdminArticlesRouteRouteImport } from './routes/admin/articles/route'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminProjectsIndexRouteImport } from './routes/admin/projects/index'
import { Route as AdminArticlesIndexRouteImport } from './routes/admin/articles/index'
import { Route as ProjectsIdEditRouteImport } from './routes/projects/$id.edit'
import { Route as AdminProjectsCreateRouteImport } from './routes/admin/projects/create'
import { Route as AdminArticlesSlugRouteImport } from './routes/admin/articles/$slug'
import { Route as ArticlesUserIdSlugEditRouteImport } from './routes/articles/$userId.$slug.edit'
import { Route as AdminUsersUsersIdRouteImport } from './routes/admin/users/users.$id'
import { Route as AdminProjectsIdEditRouteImport } from './routes/admin/projects/$id.edit'
import { Route as AdminUsersUsersIdEditRouteImport } from './routes/admin/users/users.$id.edit'
import { Route as AdminArticlesUserIdSlugEditRouteImport } from './routes/admin/articles/$userId.$slug.edit'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRouteRoute = ProjectsRouteRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRouteRoute = ArticlesRouteRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRouteRoute = AccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRouteRoute,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArticlesRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRouteRoute,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsRouteRoute,
} as any)
const ArticlesCreateRoute = ArticlesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ArticlesRouteRoute,
} as any)
const ArticlesUserIdRoute = ArticlesUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => ArticlesRouteRoute,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArticlesRouteRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AccountVerifyRoute = AccountVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountResetPasswordRoute = AccountResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountRegisterRoute = AccountRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountForgotPasswordRoute = AccountForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AdminUsersRouteRoute = AdminUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProjectsRouteRoute = AdminProjectsRouteRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminArticlesRouteRoute = AdminArticlesRouteRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminUsersRouteRoute,
} as any)
const AdminProjectsIndexRoute = AdminProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProjectsRouteRoute,
} as any)
const AdminArticlesIndexRoute = AdminArticlesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminArticlesRouteRoute,
} as any)
const ProjectsIdEditRoute = ProjectsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const AdminProjectsCreateRoute = AdminProjectsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AdminProjectsRouteRoute,
} as any)
const AdminArticlesSlugRoute = AdminArticlesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdminArticlesRouteRoute,
} as any)
const ArticlesUserIdSlugEditRoute = ArticlesUserIdSlugEditRouteImport.update({
  id: '/$slug/edit',
  path: '/$slug/edit',
  getParentRoute: () => ArticlesUserIdRoute,
} as any)
const AdminUsersUsersIdRoute = AdminUsersUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => AdminUsersRouteRoute,
} as any)
const AdminProjectsIdEditRoute = AdminProjectsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminProjectsRouteRoute,
} as any)
const AdminUsersUsersIdEditRoute = AdminUsersUsersIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AdminUsersUsersIdRoute,
} as any)
const AdminArticlesUserIdSlugEditRoute =
  AdminArticlesUserIdSlugEditRouteImport.update({
    id: '/$userId/$slug/edit',
    path: '/$userId/$slug/edit',
    getParentRoute: () => AdminArticlesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/articles': typeof ArticlesRouteRouteWithChildren
  '/projects': typeof ProjectsRouteRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/admin/articles': typeof AdminArticlesRouteRouteWithChildren
  '/admin/projects': typeof AdminProjectsRouteRouteWithChildren
  '/admin/users': typeof AdminUsersRouteRouteWithChildren
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account/verify': typeof AccountVerifyRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/$userId': typeof ArticlesUserIdRouteWithChildren
  '/articles/create': typeof ArticlesCreateRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/admin/articles/$slug': typeof AdminArticlesSlugRoute
  '/admin/projects/create': typeof AdminProjectsCreateRoute
  '/projects/$id/edit': typeof ProjectsIdEditRoute
  '/admin/articles/': typeof AdminArticlesIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/projects/$id/edit': typeof AdminProjectsIdEditRoute
  '/admin/users/users/$id': typeof AdminUsersUsersIdRouteWithChildren
  '/articles/$userId/$slug/edit': typeof ArticlesUserIdSlugEditRoute
  '/admin/articles/$userId/$slug/edit': typeof AdminArticlesUserIdSlugEditRoute
  '/admin/users/users/$id/edit': typeof AdminUsersUsersIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account/verify': typeof AccountVerifyRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/$userId': typeof ArticlesUserIdRouteWithChildren
  '/articles/create': typeof ArticlesCreateRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/articles': typeof ArticlesIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/admin/articles/$slug': typeof AdminArticlesSlugRoute
  '/admin/projects/create': typeof AdminProjectsCreateRoute
  '/projects/$id/edit': typeof ProjectsIdEditRoute
  '/admin/articles': typeof AdminArticlesIndexRoute
  '/admin/projects': typeof AdminProjectsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/projects/$id/edit': typeof AdminProjectsIdEditRoute
  '/admin/users/users/$id': typeof AdminUsersUsersIdRouteWithChildren
  '/articles/$userId/$slug/edit': typeof ArticlesUserIdSlugEditRoute
  '/admin/articles/$userId/$slug/edit': typeof AdminArticlesUserIdSlugEditRoute
  '/admin/users/users/$id/edit': typeof AdminUsersUsersIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/articles': typeof ArticlesRouteRouteWithChildren
  '/projects': typeof ProjectsRouteRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/admin/articles': typeof AdminArticlesRouteRouteWithChildren
  '/admin/projects': typeof AdminProjectsRouteRouteWithChildren
  '/admin/users': typeof AdminUsersRouteRouteWithChildren
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account/verify': typeof AccountVerifyRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/$userId': typeof ArticlesUserIdRouteWithChildren
  '/articles/create': typeof ArticlesCreateRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/admin/articles/$slug': typeof AdminArticlesSlugRoute
  '/admin/projects/create': typeof AdminProjectsCreateRoute
  '/projects/$id/edit': typeof ProjectsIdEditRoute
  '/admin/articles/': typeof AdminArticlesIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/projects/$id/edit': typeof AdminProjectsIdEditRoute
  '/admin/users/users/$id': typeof AdminUsersUsersIdRouteWithChildren
  '/articles/$userId/$slug/edit': typeof ArticlesUserIdSlugEditRoute
  '/admin/articles/$userId/$slug/edit': typeof AdminArticlesUserIdSlugEditRoute
  '/admin/users/users/$id/edit': typeof AdminUsersUsersIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/articles'
    | '/projects'
    | '/categories'
    | '/contact'
    | '/admin/articles'
    | '/admin/projects'
    | '/admin/users'
    | '/account/forgot-password'
    | '/account/register'
    | '/account/reset-password'
    | '/account/settings'
    | '/account/verify'
    | '/admin/categories'
    | '/articles/$slug'
    | '/articles/$userId'
    | '/articles/create'
    | '/projects/$id'
    | '/account/'
    | '/admin/'
    | '/articles/'
    | '/projects/'
    | '/admin/articles/$slug'
    | '/admin/projects/create'
    | '/projects/$id/edit'
    | '/admin/articles/'
    | '/admin/projects/'
    | '/admin/users/'
    | '/admin/projects/$id/edit'
    | '/admin/users/users/$id'
    | '/articles/$userId/$slug/edit'
    | '/admin/articles/$userId/$slug/edit'
    | '/admin/users/users/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories'
    | '/contact'
    | '/account/forgot-password'
    | '/account/register'
    | '/account/reset-password'
    | '/account/settings'
    | '/account/verify'
    | '/admin/categories'
    | '/articles/$slug'
    | '/articles/$userId'
    | '/articles/create'
    | '/projects/$id'
    | '/account'
    | '/admin'
    | '/articles'
    | '/projects'
    | '/admin/articles/$slug'
    | '/admin/projects/create'
    | '/projects/$id/edit'
    | '/admin/articles'
    | '/admin/projects'
    | '/admin/users'
    | '/admin/projects/$id/edit'
    | '/admin/users/users/$id'
    | '/articles/$userId/$slug/edit'
    | '/admin/articles/$userId/$slug/edit'
    | '/admin/users/users/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/articles'
    | '/projects'
    | '/categories'
    | '/contact'
    | '/admin/articles'
    | '/admin/projects'
    | '/admin/users'
    | '/account/forgot-password'
    | '/account/register'
    | '/account/reset-password'
    | '/account/settings'
    | '/account/verify'
    | '/admin/categories'
    | '/articles/$slug'
    | '/articles/$userId'
    | '/articles/create'
    | '/projects/$id'
    | '/account/'
    | '/admin/'
    | '/articles/'
    | '/projects/'
    | '/admin/articles/$slug'
    | '/admin/projects/create'
    | '/projects/$id/edit'
    | '/admin/articles/'
    | '/admin/projects/'
    | '/admin/users/'
    | '/admin/projects/$id/edit'
    | '/admin/users/users/$id'
    | '/articles/$userId/$slug/edit'
    | '/admin/articles/$userId/$slug/edit'
    | '/admin/users/users/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRouteRoute: typeof AccountRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ArticlesRouteRoute: typeof ArticlesRouteRouteWithChildren
  ProjectsRouteRoute: typeof ProjectsRouteRouteWithChildren
  CategoriesRoute: typeof CategoriesRoute
  ContactRoute: typeof ContactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRouteRoute
    }
    '/articles/': {
      id: '/articles/'
      path: '/'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof ArticlesRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof ProjectsRouteRoute
    }
    '/articles/create': {
      id: '/articles/create'
      path: '/create'
      fullPath: '/articles/create'
      preLoaderRoute: typeof ArticlesCreateRouteImport
      parentRoute: typeof ArticlesRouteRoute
    }
    '/articles/$userId': {
      id: '/articles/$userId'
      path: '/$userId'
      fullPath: '/articles/$userId'
      preLoaderRoute: typeof ArticlesUserIdRouteImport
      parentRoute: typeof ArticlesRouteRoute
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof ArticlesRouteRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/account/verify': {
      id: '/account/verify'
      path: '/verify'
      fullPath: '/account/verify'
      preLoaderRoute: typeof AccountVerifyRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/reset-password': {
      id: '/account/reset-password'
      path: '/reset-password'
      fullPath: '/account/reset-password'
      preLoaderRoute: typeof AccountResetPasswordRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/register': {
      id: '/account/register'
      path: '/register'
      fullPath: '/account/register'
      preLoaderRoute: typeof AccountRegisterRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/forgot-password': {
      id: '/account/forgot-password'
      path: '/forgot-password'
      fullPath: '/account/forgot-password'
      preLoaderRoute: typeof AccountForgotPasswordRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/articles': {
      id: '/admin/articles'
      path: '/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AdminArticlesRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminUsersRouteRoute
    }
    '/admin/projects/': {
      id: '/admin/projects/'
      path: '/'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AdminProjectsIndexRouteImport
      parentRoute: typeof AdminProjectsRouteRoute
    }
    '/admin/articles/': {
      id: '/admin/articles/'
      path: '/'
      fullPath: '/admin/articles/'
      preLoaderRoute: typeof AdminArticlesIndexRouteImport
      parentRoute: typeof AdminArticlesRouteRoute
    }
    '/projects/$id/edit': {
      id: '/projects/$id/edit'
      path: '/edit'
      fullPath: '/projects/$id/edit'
      preLoaderRoute: typeof ProjectsIdEditRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/admin/projects/create': {
      id: '/admin/projects/create'
      path: '/create'
      fullPath: '/admin/projects/create'
      preLoaderRoute: typeof AdminProjectsCreateRouteImport
      parentRoute: typeof AdminProjectsRouteRoute
    }
    '/admin/articles/$slug': {
      id: '/admin/articles/$slug'
      path: '/$slug'
      fullPath: '/admin/articles/$slug'
      preLoaderRoute: typeof AdminArticlesSlugRouteImport
      parentRoute: typeof AdminArticlesRouteRoute
    }
    '/articles/$userId/$slug/edit': {
      id: '/articles/$userId/$slug/edit'
      path: '/$slug/edit'
      fullPath: '/articles/$userId/$slug/edit'
      preLoaderRoute: typeof ArticlesUserIdSlugEditRouteImport
      parentRoute: typeof ArticlesUserIdRoute
    }
    '/admin/users/users/$id': {
      id: '/admin/users/users/$id'
      path: '/users/$id'
      fullPath: '/admin/users/users/$id'
      preLoaderRoute: typeof AdminUsersUsersIdRouteImport
      parentRoute: typeof AdminUsersRouteRoute
    }
    '/admin/projects/$id/edit': {
      id: '/admin/projects/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/projects/$id/edit'
      preLoaderRoute: typeof AdminProjectsIdEditRouteImport
      parentRoute: typeof AdminProjectsRouteRoute
    }
    '/admin/users/users/$id/edit': {
      id: '/admin/users/users/$id/edit'
      path: '/edit'
      fullPath: '/admin/users/users/$id/edit'
      preLoaderRoute: typeof AdminUsersUsersIdEditRouteImport
      parentRoute: typeof AdminUsersUsersIdRoute
    }
    '/admin/articles/$userId/$slug/edit': {
      id: '/admin/articles/$userId/$slug/edit'
      path: '/$userId/$slug/edit'
      fullPath: '/admin/articles/$userId/$slug/edit'
      preLoaderRoute: typeof AdminArticlesUserIdSlugEditRouteImport
      parentRoute: typeof AdminArticlesRouteRoute
    }
  }
}

interface AccountRouteRouteChildren {
  AccountForgotPasswordRoute: typeof AccountForgotPasswordRoute
  AccountRegisterRoute: typeof AccountRegisterRoute
  AccountResetPasswordRoute: typeof AccountResetPasswordRoute
  AccountSettingsRoute: typeof AccountSettingsRoute
  AccountVerifyRoute: typeof AccountVerifyRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteRouteChildren: AccountRouteRouteChildren = {
  AccountForgotPasswordRoute: AccountForgotPasswordRoute,
  AccountRegisterRoute: AccountRegisterRoute,
  AccountResetPasswordRoute: AccountResetPasswordRoute,
  AccountSettingsRoute: AccountSettingsRoute,
  AccountVerifyRoute: AccountVerifyRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteRouteWithChildren = AccountRouteRoute._addFileChildren(
  AccountRouteRouteChildren,
)

interface AdminArticlesRouteRouteChildren {
  AdminArticlesSlugRoute: typeof AdminArticlesSlugRoute
  AdminArticlesIndexRoute: typeof AdminArticlesIndexRoute
  AdminArticlesUserIdSlugEditRoute: typeof AdminArticlesUserIdSlugEditRoute
}

const AdminArticlesRouteRouteChildren: AdminArticlesRouteRouteChildren = {
  AdminArticlesSlugRoute: AdminArticlesSlugRoute,
  AdminArticlesIndexRoute: AdminArticlesIndexRoute,
  AdminArticlesUserIdSlugEditRoute: AdminArticlesUserIdSlugEditRoute,
}

const AdminArticlesRouteRouteWithChildren =
  AdminArticlesRouteRoute._addFileChildren(AdminArticlesRouteRouteChildren)

interface AdminProjectsRouteRouteChildren {
  AdminProjectsCreateRoute: typeof AdminProjectsCreateRoute
  AdminProjectsIndexRoute: typeof AdminProjectsIndexRoute
  AdminProjectsIdEditRoute: typeof AdminProjectsIdEditRoute
}

const AdminProjectsRouteRouteChildren: AdminProjectsRouteRouteChildren = {
  AdminProjectsCreateRoute: AdminProjectsCreateRoute,
  AdminProjectsIndexRoute: AdminProjectsIndexRoute,
  AdminProjectsIdEditRoute: AdminProjectsIdEditRoute,
}

const AdminProjectsRouteRouteWithChildren =
  AdminProjectsRouteRoute._addFileChildren(AdminProjectsRouteRouteChildren)

interface AdminUsersUsersIdRouteChildren {
  AdminUsersUsersIdEditRoute: typeof AdminUsersUsersIdEditRoute
}

const AdminUsersUsersIdRouteChildren: AdminUsersUsersIdRouteChildren = {
  AdminUsersUsersIdEditRoute: AdminUsersUsersIdEditRoute,
}

const AdminUsersUsersIdRouteWithChildren =
  AdminUsersUsersIdRoute._addFileChildren(AdminUsersUsersIdRouteChildren)

interface AdminUsersRouteRouteChildren {
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminUsersUsersIdRoute: typeof AdminUsersUsersIdRouteWithChildren
}

const AdminUsersRouteRouteChildren: AdminUsersRouteRouteChildren = {
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminUsersUsersIdRoute: AdminUsersUsersIdRouteWithChildren,
}

const AdminUsersRouteRouteWithChildren = AdminUsersRouteRoute._addFileChildren(
  AdminUsersRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminArticlesRouteRoute: typeof AdminArticlesRouteRouteWithChildren
  AdminProjectsRouteRoute: typeof AdminProjectsRouteRouteWithChildren
  AdminUsersRouteRoute: typeof AdminUsersRouteRouteWithChildren
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminArticlesRouteRoute: AdminArticlesRouteRouteWithChildren,
  AdminProjectsRouteRoute: AdminProjectsRouteRouteWithChildren,
  AdminUsersRouteRoute: AdminUsersRouteRouteWithChildren,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ArticlesUserIdRouteChildren {
  ArticlesUserIdSlugEditRoute: typeof ArticlesUserIdSlugEditRoute
}

const ArticlesUserIdRouteChildren: ArticlesUserIdRouteChildren = {
  ArticlesUserIdSlugEditRoute: ArticlesUserIdSlugEditRoute,
}

const ArticlesUserIdRouteWithChildren = ArticlesUserIdRoute._addFileChildren(
  ArticlesUserIdRouteChildren,
)

interface ArticlesRouteRouteChildren {
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ArticlesUserIdRoute: typeof ArticlesUserIdRouteWithChildren
  ArticlesCreateRoute: typeof ArticlesCreateRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
}

const ArticlesRouteRouteChildren: ArticlesRouteRouteChildren = {
  ArticlesSlugRoute: ArticlesSlugRoute,
  ArticlesUserIdRoute: ArticlesUserIdRouteWithChildren,
  ArticlesCreateRoute: ArticlesCreateRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
}

const ArticlesRouteRouteWithChildren = ArticlesRouteRoute._addFileChildren(
  ArticlesRouteRouteChildren,
)

interface ProjectsIdRouteChildren {
  ProjectsIdEditRoute: typeof ProjectsIdEditRoute
}

const ProjectsIdRouteChildren: ProjectsIdRouteChildren = {
  ProjectsIdEditRoute: ProjectsIdEditRoute,
}

const ProjectsIdRouteWithChildren = ProjectsIdRoute._addFileChildren(
  ProjectsIdRouteChildren,
)

interface ProjectsRouteRouteChildren {
  ProjectsIdRoute: typeof ProjectsIdRouteWithChildren
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteRouteChildren: ProjectsRouteRouteChildren = {
  ProjectsIdRoute: ProjectsIdRouteWithChildren,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteRouteWithChildren = ProjectsRouteRoute._addFileChildren(
  ProjectsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRouteRoute: AccountRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ArticlesRouteRoute: ArticlesRouteRouteWithChildren,
  ProjectsRouteRoute: ProjectsRouteRouteWithChildren,
  CategoriesRoute: CategoriesRoute,
  ContactRoute: ContactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
