/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as ToolsProcessRouteImport } from './routes/tools-process'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as SplatRouteImport } from './routes/$'
import { Route as TestimonialsRouteRouteImport } from './routes/testimonials/route'
import { Route as ProjectsRouteRouteImport } from './routes/projects/route'
import { Route as CasesRouteRouteImport } from './routes/cases/route'
import { Route as AccountRouteRouteImport } from './routes/account/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestimonialsIndexRouteImport } from './routes/testimonials/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as CasesIndexRouteImport } from './routes/cases/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as TestimonialsNewRouteImport } from './routes/testimonials/new'
import { Route as ProjectsNewRouteImport } from './routes/projects/new'
import { Route as CasesSlugRouteImport } from './routes/cases/$slug'
import { Route as AccountRegisterRouteImport } from './routes/account/register'
import { Route as ProjectsSlugEditRouteImport } from './routes/projects/$slug.edit'
import { Route as ProjectsSlugDetailsRouteImport } from './routes/projects/$slug.details'
import { Route as CasesNewProjectIdRouteImport } from './routes/cases/new.$projectId'
import { Route as CasesEditCaseIdRouteImport } from './routes/cases/edit.$caseId'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsProcessRoute = ToolsProcessRouteImport.update({
  id: '/tools-process',
  path: '/tools-process',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRouteRoute = TestimonialsRouteRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRouteRoute = ProjectsRouteRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRouteRoute = CasesRouteRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRouteRoute = AccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsIndexRoute = TestimonialsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TestimonialsRouteRoute,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRouteRoute,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CasesRouteRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRouteRoute,
} as any)
const TestimonialsNewRoute = TestimonialsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TestimonialsRouteRoute,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProjectsRouteRoute,
} as any)
const CasesSlugRoute = CasesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CasesRouteRoute,
} as any)
const AccountRegisterRoute = AccountRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AccountRouteRoute,
} as any)
const ProjectsSlugEditRoute = ProjectsSlugEditRouteImport.update({
  id: '/$slug/edit',
  path: '/$slug/edit',
  getParentRoute: () => ProjectsRouteRoute,
} as any)
const ProjectsSlugDetailsRoute = ProjectsSlugDetailsRouteImport.update({
  id: '/$slug/details',
  path: '/$slug/details',
  getParentRoute: () => ProjectsRouteRoute,
} as any)
const CasesNewProjectIdRoute = CasesNewProjectIdRouteImport.update({
  id: '/new/$projectId',
  path: '/new/$projectId',
  getParentRoute: () => CasesRouteRoute,
} as any)
const CasesEditCaseIdRoute = CasesEditCaseIdRouteImport.update({
  id: '/edit/$caseId',
  path: '/edit/$caseId',
  getParentRoute: () => CasesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/cases': typeof CasesRouteRouteWithChildren
  '/projects': typeof ProjectsRouteRouteWithChildren
  '/testimonials': typeof TestimonialsRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/contacts': typeof ContactsRoute
  '/services': typeof ServicesRoute
  '/tools-process': typeof ToolsProcessRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/account/register': typeof AccountRegisterRoute
  '/cases/$slug': typeof CasesSlugRoute
  '/projects/new': typeof ProjectsNewRoute
  '/testimonials/new': typeof TestimonialsNewRoute
  '/account/': typeof AccountIndexRoute
  '/cases/': typeof CasesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/testimonials/': typeof TestimonialsIndexRoute
  '/cases/edit/$caseId': typeof CasesEditCaseIdRoute
  '/cases/new/$projectId': typeof CasesNewProjectIdRoute
  '/projects/$slug/details': typeof ProjectsSlugDetailsRoute
  '/projects/$slug/edit': typeof ProjectsSlugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/contacts': typeof ContactsRoute
  '/services': typeof ServicesRoute
  '/tools-process': typeof ToolsProcessRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/account/register': typeof AccountRegisterRoute
  '/cases/$slug': typeof CasesSlugRoute
  '/projects/new': typeof ProjectsNewRoute
  '/testimonials/new': typeof TestimonialsNewRoute
  '/account': typeof AccountIndexRoute
  '/cases': typeof CasesIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/testimonials': typeof TestimonialsIndexRoute
  '/cases/edit/$caseId': typeof CasesEditCaseIdRoute
  '/cases/new/$projectId': typeof CasesNewProjectIdRoute
  '/projects/$slug/details': typeof ProjectsSlugDetailsRoute
  '/projects/$slug/edit': typeof ProjectsSlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/cases': typeof CasesRouteRouteWithChildren
  '/projects': typeof ProjectsRouteRouteWithChildren
  '/testimonials': typeof TestimonialsRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/contacts': typeof ContactsRoute
  '/services': typeof ServicesRoute
  '/tools-process': typeof ToolsProcessRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/account/register': typeof AccountRegisterRoute
  '/cases/$slug': typeof CasesSlugRoute
  '/projects/new': typeof ProjectsNewRoute
  '/testimonials/new': typeof TestimonialsNewRoute
  '/account/': typeof AccountIndexRoute
  '/cases/': typeof CasesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/testimonials/': typeof TestimonialsIndexRoute
  '/cases/edit/$caseId': typeof CasesEditCaseIdRoute
  '/cases/new/$projectId': typeof CasesNewProjectIdRoute
  '/projects/$slug/details': typeof ProjectsSlugDetailsRoute
  '/projects/$slug/edit': typeof ProjectsSlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/cases'
    | '/projects'
    | '/testimonials'
    | '/$'
    | '/contacts'
    | '/services'
    | '/tools-process'
    | '/unauthorized'
    | '/account/register'
    | '/cases/$slug'
    | '/projects/new'
    | '/testimonials/new'
    | '/account/'
    | '/cases/'
    | '/projects/'
    | '/testimonials/'
    | '/cases/edit/$caseId'
    | '/cases/new/$projectId'
    | '/projects/$slug/details'
    | '/projects/$slug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/contacts'
    | '/services'
    | '/tools-process'
    | '/unauthorized'
    | '/account/register'
    | '/cases/$slug'
    | '/projects/new'
    | '/testimonials/new'
    | '/account'
    | '/cases'
    | '/projects'
    | '/testimonials'
    | '/cases/edit/$caseId'
    | '/cases/new/$projectId'
    | '/projects/$slug/details'
    | '/projects/$slug/edit'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/cases'
    | '/projects'
    | '/testimonials'
    | '/$'
    | '/contacts'
    | '/services'
    | '/tools-process'
    | '/unauthorized'
    | '/account/register'
    | '/cases/$slug'
    | '/projects/new'
    | '/testimonials/new'
    | '/account/'
    | '/cases/'
    | '/projects/'
    | '/testimonials/'
    | '/cases/edit/$caseId'
    | '/cases/new/$projectId'
    | '/projects/$slug/details'
    | '/projects/$slug/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRouteRoute: typeof AccountRouteRouteWithChildren
  CasesRouteRoute: typeof CasesRouteRouteWithChildren
  ProjectsRouteRoute: typeof ProjectsRouteRouteWithChildren
  TestimonialsRouteRoute: typeof TestimonialsRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  ContactsRoute: typeof ContactsRoute
  ServicesRoute: typeof ServicesRoute
  ToolsProcessRoute: typeof ToolsProcessRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools-process': {
      id: '/tools-process'
      path: '/tools-process'
      fullPath: '/tools-process'
      preLoaderRoute: typeof ToolsProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials/': {
      id: '/testimonials/'
      path: '/'
      fullPath: '/testimonials/'
      preLoaderRoute: typeof TestimonialsIndexRouteImport
      parentRoute: typeof TestimonialsRouteRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRouteRoute
    }
    '/cases/': {
      id: '/cases/'
      path: '/'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof CasesRouteRoute
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/testimonials/new': {
      id: '/testimonials/new'
      path: '/new'
      fullPath: '/testimonials/new'
      preLoaderRoute: typeof TestimonialsNewRouteImport
      parentRoute: typeof TestimonialsRouteRoute
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof ProjectsRouteRoute
    }
    '/cases/$slug': {
      id: '/cases/$slug'
      path: '/$slug'
      fullPath: '/cases/$slug'
      preLoaderRoute: typeof CasesSlugRouteImport
      parentRoute: typeof CasesRouteRoute
    }
    '/account/register': {
      id: '/account/register'
      path: '/register'
      fullPath: '/account/register'
      preLoaderRoute: typeof AccountRegisterRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/projects/$slug/edit': {
      id: '/projects/$slug/edit'
      path: '/$slug/edit'
      fullPath: '/projects/$slug/edit'
      preLoaderRoute: typeof ProjectsSlugEditRouteImport
      parentRoute: typeof ProjectsRouteRoute
    }
    '/projects/$slug/details': {
      id: '/projects/$slug/details'
      path: '/$slug/details'
      fullPath: '/projects/$slug/details'
      preLoaderRoute: typeof ProjectsSlugDetailsRouteImport
      parentRoute: typeof ProjectsRouteRoute
    }
    '/cases/new/$projectId': {
      id: '/cases/new/$projectId'
      path: '/new/$projectId'
      fullPath: '/cases/new/$projectId'
      preLoaderRoute: typeof CasesNewProjectIdRouteImport
      parentRoute: typeof CasesRouteRoute
    }
    '/cases/edit/$caseId': {
      id: '/cases/edit/$caseId'
      path: '/edit/$caseId'
      fullPath: '/cases/edit/$caseId'
      preLoaderRoute: typeof CasesEditCaseIdRouteImport
      parentRoute: typeof CasesRouteRoute
    }
  }
}

interface AccountRouteRouteChildren {
  AccountRegisterRoute: typeof AccountRegisterRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteRouteChildren: AccountRouteRouteChildren = {
  AccountRegisterRoute: AccountRegisterRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteRouteWithChildren = AccountRouteRoute._addFileChildren(
  AccountRouteRouteChildren,
)

interface CasesRouteRouteChildren {
  CasesSlugRoute: typeof CasesSlugRoute
  CasesIndexRoute: typeof CasesIndexRoute
  CasesEditCaseIdRoute: typeof CasesEditCaseIdRoute
  CasesNewProjectIdRoute: typeof CasesNewProjectIdRoute
}

const CasesRouteRouteChildren: CasesRouteRouteChildren = {
  CasesSlugRoute: CasesSlugRoute,
  CasesIndexRoute: CasesIndexRoute,
  CasesEditCaseIdRoute: CasesEditCaseIdRoute,
  CasesNewProjectIdRoute: CasesNewProjectIdRoute,
}

const CasesRouteRouteWithChildren = CasesRouteRoute._addFileChildren(
  CasesRouteRouteChildren,
)

interface ProjectsRouteRouteChildren {
  ProjectsNewRoute: typeof ProjectsNewRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsSlugDetailsRoute: typeof ProjectsSlugDetailsRoute
  ProjectsSlugEditRoute: typeof ProjectsSlugEditRoute
}

const ProjectsRouteRouteChildren: ProjectsRouteRouteChildren = {
  ProjectsNewRoute: ProjectsNewRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsSlugDetailsRoute: ProjectsSlugDetailsRoute,
  ProjectsSlugEditRoute: ProjectsSlugEditRoute,
}

const ProjectsRouteRouteWithChildren = ProjectsRouteRoute._addFileChildren(
  ProjectsRouteRouteChildren,
)

interface TestimonialsRouteRouteChildren {
  TestimonialsNewRoute: typeof TestimonialsNewRoute
  TestimonialsIndexRoute: typeof TestimonialsIndexRoute
}

const TestimonialsRouteRouteChildren: TestimonialsRouteRouteChildren = {
  TestimonialsNewRoute: TestimonialsNewRoute,
  TestimonialsIndexRoute: TestimonialsIndexRoute,
}

const TestimonialsRouteRouteWithChildren =
  TestimonialsRouteRoute._addFileChildren(TestimonialsRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRouteRoute: AccountRouteRouteWithChildren,
  CasesRouteRoute: CasesRouteRouteWithChildren,
  ProjectsRouteRoute: ProjectsRouteRouteWithChildren,
  TestimonialsRouteRoute: TestimonialsRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  ContactsRoute: ContactsRoute,
  ServicesRoute: ServicesRoute,
  ToolsProcessRoute: ToolsProcessRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
